/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PursePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// purseView.ts
var import_obsidian = require("obsidian");
var PURSE_VIEW_TYPE = "purse-view";

// modals.ts
var import_obsidian2 = require("obsidian");
var DeleteConfirmModal = class extends import_obsidian2.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    this.titleEl.setText("\u786E\u8BA4\u5220\u9664");
    this.contentEl.createDiv({ text: "\u786E\u5B9A\u8981\u5220\u9664\u8FD9\u6761\u8BB0\u5F55\u5417\uFF1F\u6B64\u64CD\u4F5C\u4E0D\u53EF\u64A4\u9500\u3002" });
    const buttonContainer = this.contentEl.createDiv("modal-button-container");
    const confirmBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u786E\u8BA4\u5220\u9664").onClick(() => {
      this.onConfirm(true);
      this.close();
    });
    confirmBtn.buttonEl.addClass("mod-cta");
    const cancelBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u53D6\u6D88").onClick(() => {
      this.onConfirm(false);
      this.close();
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};
var AddRecordModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, file, date, insertIndex, onSuccess) {
    super(app);
    this.plugin = plugin;
    this.file = file;
    this.date = date;
    this.insertIndex = insertIndex;
    this.onSuccess = onSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("purse-add-modal");
    contentEl.createEl("h2", { text: "\u6DFB\u52A0\u8BB0\u5F55" });
    const typeContainer = contentEl.createDiv();
    typeContainer.createEl("label", { text: "\u7C7B\u578B\uFF1A", attr: { for: "type-select" } });
    const typeSelect = typeContainer.createEl("select", { attr: { id: "type-select" } });
    typeSelect.createEl("option", { text: "\u652F\u51FA", attr: { value: "\u652F\u51FA" } });
    typeSelect.createEl("option", { text: "\u6536\u5165", attr: { value: "\u6536\u5165" } });
    this.typeComponent = new import_obsidian2.TextComponent(typeContainer);
    this.typeComponent.inputEl.replaceWith(typeSelect);
    const categoryContainer = contentEl.createDiv();
    categoryContainer.createEl("label", { text: "\u5206\u7C7B\uFF1A", attr: { for: "category-input" } });
    this.categoryComponent = new import_obsidian2.TextComponent(categoryContainer);
    this.categoryComponent.inputEl.id = "category-input";
    const tagContainer = contentEl.createDiv();
    tagContainer.createEl("label", { text: "\u6807\u7B7E\uFF1A", attr: { for: "tag-input" } });
    this.tagComponent = new import_obsidian2.TextComponent(tagContainer);
    this.tagComponent.inputEl.id = "tag-input";
    const amountContainer = contentEl.createDiv();
    amountContainer.createEl("label", { text: "\u6570\u989D\uFF1A", attr: { for: "amount-input" } });
    this.amountComponent = new import_obsidian2.TextComponent(amountContainer);
    this.amountComponent.inputEl.id = "amount-input";
    this.amountComponent.inputEl.type = "number";
    this.amountComponent.inputEl.step = "0.01";
    this.amountComponent.setPlaceholder("0.00");
    const noteContainer = contentEl.createDiv();
    noteContainer.createEl("label", { text: "\u5907\u6CE8\uFF1A", attr: { for: "note-input" } });
    this.noteComponent = new import_obsidian2.TextComponent(noteContainer);
    this.noteComponent.inputEl.id = "note-input";
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const confirmBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u786E\u8BA4").onClick(() => this.addRecord(typeSelect.value));
    confirmBtn.buttonEl.addClass("mod-cta");
    const cancelBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u53D6\u6D88").onClick(() => this.close());
  }
  async addRecord(type) {
    const category = this.categoryComponent.getValue().trim();
    const tag = this.tagComponent.getValue().trim();
    const amount = parseFloat(this.amountComponent.getValue());
    const note = this.noteComponent.getValue().trim();
    if (!type || !category || isNaN(amount) || amount <= 0) {
      new import_obsidian2.Notice("\u8BF7\u586B\u5199\u7C7B\u578B\u3001\u5206\u7C7B\u548C\u6570\u989D\uFF08\u6570\u989D\u5FC5\u987B\u5927\u4E8E0\uFF09");
      return;
    }
    const formattedAmount = amount.toFixed(2);
    const newRow = `| ${type} | ${category} | ${tag || ""} | ${formattedAmount} | ${note || ""} |`;
    try {
      const content = await this.app.vault.read(this.file);
      const lines = content.split("\n");
      let dateIndex = -1;
      for (let i = 0; i < lines.length; i++) {
        const dateMatch = lines[i].match(/^## (\d+)号$/);
        if (dateMatch && dateMatch[1] === this.date) {
          dateIndex = i;
          break;
        }
      }
      if (dateIndex === -1) {
        new import_obsidian2.Notice("\u65E0\u6CD5\u627E\u5230\u76EE\u6807\u65E5\u671F\uFF0C\u8BF7\u68C0\u67E5\u6587\u4EF6\u683C\u5F0F");
        return;
      }
      let foundTableHeader = false;
      let headerSeparatorIndex = -1;
      let lastDataRowIndex = -1;
      for (let i = dateIndex + 1; i < lines.length; i++) {
        const trimmedLine = lines[i].trim();
        if (trimmedLine.match(/^## \d+号$/)) {
          break;
        }
        if (!foundTableHeader && trimmedLine === "") {
          continue;
        }
        if (!foundTableHeader && this.plugin.isPurseTableHeader(trimmedLine)) {
          foundTableHeader = true;
          continue;
        }
        if (foundTableHeader && headerSeparatorIndex === -1) {
          if (trimmedLine.match(/^\|(\s*[\-:]+\s*\|)+$/)) {
            headerSeparatorIndex = i;
            continue;
          }
          if (trimmedLine !== "") {
            break;
          }
        }
        if (headerSeparatorIndex >= 0) {
          if (trimmedLine === "") {
            break;
          }
          const rowMatch = trimmedLine.match(/^\| (支出|收入) \| (.+) \| (.*) \| (\d+\.\d{2}) \| (.*) \|$/);
          if (rowMatch) {
            lastDataRowIndex = i;
          } else if (trimmedLine.startsWith("|")) {
            break;
          }
        }
      }
      let insertPos = -1;
      if (lastDataRowIndex >= 0) {
        insertPos = lastDataRowIndex + 1;
      } else if (headerSeparatorIndex >= 0) {
        insertPos = headerSeparatorIndex + 1;
      }
      if (insertPos >= 0) {
        lines.splice(insertPos, 0, newRow);
        await this.app.vault.modify(this.file, lines.join("\n"));
        await this.plugin.formatFile(this.file);
        new import_obsidian2.Notice("\u8BB0\u5F55\u5DF2\u6DFB\u52A0");
        this.close();
        this.onSuccess();
      } else {
        let errorMsg = "\u65E0\u6CD5\u627E\u5230\u63D2\u5165\u4F4D\u7F6E";
        if (!foundTableHeader) {
          errorMsg += "\uFF1A\u672A\u627E\u5230\u8868\u5934";
        } else if (headerSeparatorIndex === -1) {
          errorMsg += "\uFF1A\u672A\u627E\u5230\u8868\u5934\u5206\u9694\u884C";
        }
        new import_obsidian2.Notice(errorMsg + "\uFF0C\u8BF7\u68C0\u67E5\u6587\u4EF6\u683C\u5F0F");
        console.error("\u63D2\u5165\u4F4D\u7F6E\u67E5\u627E\u5931\u8D25:", {
          date: this.date,
          dateIndex,
          foundTableHeader,
          headerSeparatorIndex,
          lastDataRowIndex
        });
      }
    } catch (error) {
      console.error("\u6DFB\u52A0\u8BB0\u5F55\u65F6\u51FA\u9519:", error);
      new import_obsidian2.Notice("\u6DFB\u52A0\u8BB0\u5F55\u5931\u8D25: " + error.message);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var EditRecordModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, file, date, oldType, oldCategory, oldTag, oldAmount, oldNote, oldRowContent, onSuccess) {
    super(app);
    this.plugin = plugin;
    this.file = file;
    this.date = date;
    this.oldType = oldType;
    this.oldCategory = oldCategory;
    this.oldTag = oldTag;
    this.oldAmount = oldAmount;
    this.oldNote = oldNote;
    this.oldRowContent = oldRowContent;
    this.onSuccess = onSuccess;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("purse-add-modal");
    contentEl.createEl("h2", { text: "\u7F16\u8F91\u8BB0\u5F55" });
    const typeContainer = contentEl.createDiv();
    typeContainer.createEl("label", { text: "\u7C7B\u578B\uFF1A", attr: { for: "type-select" } });
    const typeSelect = typeContainer.createEl("select", { attr: { id: "type-select" } });
    typeSelect.createEl("option", { text: "\u652F\u51FA", attr: { value: "\u652F\u51FA" } });
    typeSelect.createEl("option", { text: "\u6536\u5165", attr: { value: "\u6536\u5165" } });
    this.typeComponent = new import_obsidian2.TextComponent(typeContainer);
    this.typeComponent.inputEl.replaceWith(typeSelect);
    this.typeSelect = typeSelect;
    typeSelect.value = this.oldType || "\u652F\u51FA";
    const categoryContainer = contentEl.createDiv();
    categoryContainer.createEl("label", { text: "\u5206\u7C7B\uFF1A", attr: { for: "category-input" } });
    this.categoryComponent = new import_obsidian2.TextComponent(categoryContainer);
    this.categoryComponent.inputEl.id = "category-input";
    this.categoryComponent.setValue(this.oldCategory || "");
    const tagContainer = contentEl.createDiv();
    tagContainer.createEl("label", { text: "\u6807\u7B7E\uFF1A", attr: { for: "tag-input" } });
    this.tagComponent = new import_obsidian2.TextComponent(tagContainer);
    this.tagComponent.inputEl.id = "tag-input";
    this.tagComponent.setValue(this.oldTag || "");
    const amountContainer = contentEl.createDiv();
    amountContainer.createEl("label", { text: "\u6570\u989D\uFF1A", attr: { for: "amount-input" } });
    this.amountComponent = new import_obsidian2.TextComponent(amountContainer);
    this.amountComponent.inputEl.id = "amount-input";
    this.amountComponent.inputEl.type = "number";
    this.amountComponent.inputEl.step = "0.01";
    this.amountComponent.setPlaceholder("0.00");
    this.amountComponent.setValue(this.oldAmount || "");
    const noteContainer = contentEl.createDiv();
    noteContainer.createEl("label", { text: "\u5907\u6CE8\uFF1A", attr: { for: "note-input" } });
    this.noteComponent = new import_obsidian2.TextComponent(noteContainer);
    this.noteComponent.inputEl.id = "note-input";
    this.noteComponent.setValue(this.oldNote || "");
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const confirmBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u786E\u8BA4").onClick(() => this.updateRecord(typeSelect.value));
    confirmBtn.buttonEl.addClass("mod-cta");
    const cancelBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u53D6\u6D88").onClick(() => this.close());
  }
  async updateRecord(type) {
    const category = this.categoryComponent.getValue().trim();
    const tag = this.tagComponent.getValue().trim();
    const amount = parseFloat(this.amountComponent.getValue());
    const note = this.noteComponent.getValue().trim();
    if (!type || !category || isNaN(amount) || amount <= 0) {
      new import_obsidian2.Notice("\u8BF7\u586B\u5199\u7C7B\u578B\u3001\u5206\u7C7B\u548C\u6570\u989D\uFF08\u6570\u989D\u5FC5\u987B\u5927\u4E8E0\uFF09");
      return;
    }
    const formattedAmount = amount.toFixed(2);
    const newRow = `| ${type} | ${category} | ${tag || ""} | ${formattedAmount} | ${note || ""} |`;
    try {
      const content = await this.app.vault.read(this.file);
      const lines = content.split("\n");
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim() === this.oldRowContent.trim()) {
          lines[i] = newRow;
          break;
        }
      }
      await this.app.vault.modify(this.file, lines.join("\n"));
      await this.plugin.formatFile(this.file);
      new import_obsidian2.Notice("\u8BB0\u5F55\u5DF2\u66F4\u65B0");
      this.close();
      this.onSuccess();
    } catch (error) {
      console.error("\u66F4\u65B0\u8BB0\u5F55\u65F6\u51FA\u9519:", error);
      new import_obsidian2.Notice("\u66F4\u65B0\u8BB0\u5F55\u5931\u8D25: " + error.message);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var CreatePurseFileModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("purse-add-modal");
    contentEl.createEl("h2", { text: "\u521B\u5EFA\u6536\u652F\u660E\u7EC6\u6587\u4EF6" });
    const dateContainer = contentEl.createDiv();
    dateContainer.createEl("label", { text: "\u65E5\u671F\uFF08\u683C\u5F0F\uFF1Ayyyy-MM\uFF09\uFF1A", attr: { for: "date-input" } });
    this.dateComponent = new import_obsidian2.TextComponent(dateContainer);
    this.dateComponent.inputEl.id = "date-input";
    this.dateComponent.setPlaceholder("\u4F8B\u5982\uFF1A2024-01");
    const now = new Date();
    const defaultDate = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
    this.dateComponent.setValue(defaultDate);
    const buttonContainer = contentEl.createDiv("modal-button-container");
    const confirmBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u521B\u5EFA").onClick(() => this.createFile());
    confirmBtn.buttonEl.addClass("mod-cta");
    const cancelBtn = new import_obsidian2.ButtonComponent(buttonContainer).setButtonText("\u53D6\u6D88").onClick(() => this.close());
  }
  async createFile() {
    const dateStr = this.dateComponent.getValue().trim();
    const dateMatch = dateStr.match(/^(\d{4})-(\d{2})$/);
    if (!dateMatch) {
      new import_obsidian2.Notice("\u65E5\u671F\u683C\u5F0F\u4E0D\u6B63\u786E\uFF0C\u5E94\u4E3A yyyy-MM \u683C\u5F0F\uFF08\u4F8B\u5982\uFF1A2024-01\uFF09");
      return;
    }
    const year = parseInt(dateMatch[1]);
    const month = parseInt(dateMatch[2]);
    if (month < 1 || month > 12) {
      new import_obsidian2.Notice("\u6708\u4EFD\u5FC5\u987B\u5728 1-12 \u4E4B\u95F4");
      return;
    }
    try {
      await this.plugin.createPurseFile(year, month);
      new import_obsidian2.Notice("\u6587\u4EF6\u521B\u5EFA\u6210\u529F");
      this.close();
    } catch (error) {
      console.error("\u521B\u5EFA\u6587\u4EF6\u65F6\u51FA\u9519:", error);
      new import_obsidian2.Notice("\u521B\u5EFA\u6587\u4EF6\u5931\u8D25: " + error.message);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var PursePlugin = class extends import_obsidian3.Plugin {
  async onload() {
    this.registerMarkdownPostProcessor((element, context) => {
      const file = context.sourcePath ? this.app.vault.getAbstractFileByPath(context.sourcePath) : null;
      if (!(file instanceof import_obsidian3.TFile) || !this.isPurseFile(file)) {
        return;
      }
      const tables = element.querySelectorAll("table");
      tables.forEach((table) => {
        const headerRow = table.querySelector("thead tr");
        if (!headerRow)
          return;
        const headers = Array.from(headerRow.querySelectorAll("th")).map((th) => {
          var _a;
          return (_a = th.textContent) == null ? void 0 : _a.trim();
        });
        if (headers.length >= 5 && headers[0] === "\u7C7B\u578B" && headers[1] === "\u5206\u7C7B" && headers[2] === "\u6807\u7B7E" && headers[3] === "\u6570\u989D" && headers[4] === "\u5907\u6CE8") {
          this.customizeTable(table, file, context);
        }
      });
    });
    this.app.workspace.on("file-open", async (file) => {
      var _a;
      if (file && this.isPurseFile(file)) {
        const result = await this.validateFileFormat(file);
        const activeLeaf = (_a = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView)) == null ? void 0 : _a.leaf;
        if (activeLeaf) {
          if (!result.isValid) {
            await activeLeaf.setViewState({
              type: "markdown",
              state: { mode: "source" }
            });
            new import_obsidian3.Notice(`\u8D26\u5355\u683C\u5F0F\u4E0D\u5BF9\uFF1A${result.reason || "\u8BF7\u8C03\u6574"}`);
          } else {
            await activeLeaf.setViewState({
              type: "markdown",
              state: { mode: "preview" }
            });
          }
        }
      }
    });
    this.app.workspace.on("active-leaf-change", async (leaf) => {
      if ((leaf == null ? void 0 : leaf.view) instanceof import_obsidian3.MarkdownView) {
        const file = leaf.view.file;
        if (file && this.isPurseFile(file)) {
          const result = await this.validateFileFormat(file);
          if (!result.isValid) {
            await leaf.setViewState({
              type: "markdown",
              state: { mode: "source" }
            });
            new import_obsidian3.Notice(`\u8D26\u5355\u683C\u5F0F\u4E0D\u5BF9\uFF1A${result.reason || "\u8BF7\u8C03\u6574"}`);
          } else {
            await leaf.setViewState({
              type: "markdown",
              state: { mode: "preview" }
            });
          }
        }
      }
    });
    this.addCommand({
      id: "create-purse-file",
      name: "\u521B\u5EFA\u6536\u652F\u660E\u7EC6\u6587\u4EF6",
      callback: () => {
        const modal = new CreatePurseFileModal(this.app, this);
        modal.open();
      }
    });
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(PURSE_VIEW_TYPE);
  }
  /**
   * 检查文件是否是目标文件
   */
  isPurseFile(file) {
    if (!file || !file.extension) {
      return false;
    }
    if (file.extension !== "md") {
      return false;
    }
    const fileNamePattern = /^(0[1-9]|1[0-2])月$/;
    if (!file.basename || !fileNamePattern.test(file.basename)) {
      return false;
    }
    const cache = this.app.metadataCache.getFileCache(file);
    const frontmatter = cache == null ? void 0 : cache.frontmatter;
    return (frontmatter == null ? void 0 : frontmatter.purse) === true;
  }
  /**
   * 格式化文件内容（清理多余换行）
   */
  async formatFile(file) {
    try {
      const content = await this.app.vault.read(file);
      const formattedContent = this.cleanupExtraNewlines(content);
      if (formattedContent !== content) {
        await this.app.vault.modify(file, formattedContent);
      }
    } catch (error) {
      console.error("\u683C\u5F0F\u5316\u6587\u4EF6\u65F6\u51FA\u9519:", error);
    }
  }
  /**
   * 清理二级标题和表格之间的多余换行
   */
  cleanupExtraNewlines(content) {
    const lines = content.split("\n");
    const dateHeaderPattern = /^## \d+号$/;
    const cleanedLines = [];
    let i = 0;
    while (i < lines.length) {
      const line = lines[i];
      const trimmedLine = line.trim();
      if (dateHeaderPattern.test(trimmedLine)) {
        cleanedLines.push(line);
        i++;
        let emptyLineCount = 0;
        while (i < lines.length && lines[i].trim() === "") {
          emptyLineCount++;
          i++;
        }
        if (i < lines.length && this.isPurseTableHeader(lines[i].trim())) {
          if (emptyLineCount > 0) {
            cleanedLines.push("");
          }
        } else {
          for (let k = 0; k < emptyLineCount; k++) {
            cleanedLines.push("");
          }
        }
        continue;
      }
      cleanedLines.push(line);
      i++;
    }
    return cleanedLines.join("\n");
  }
  /**
   * 验证文件格式
   */
  async validateFileFormat(file) {
    console.log(`[Purse Plugin] \u5F00\u59CB\u6821\u9A8C\u6587\u4EF6\u683C\u5F0F: ${file.path}`);
    const content = await this.app.vault.read(file);
    const result = this.checkFormat(content);
    if (result.isValid) {
      console.log(`[Purse Plugin] \u6587\u4EF6\u683C\u5F0F\u6821\u9A8C\u901A\u8FC7: ${file.path}`);
      let cleanedContent = this.cleanupExtraNewlines(content);
      const cache = this.app.metadataCache.getFileCache(file);
      const frontmatter = cache == null ? void 0 : cache.frontmatter;
      if (frontmatter == null ? void 0 : frontmatter.date) {
        const dateStr = frontmatter.date;
        console.log(`[Purse Plugin] \u68C0\u6D4B\u5230 date \u5C5E\u6027: ${dateStr}`);
        const dateMatch = dateStr.match(/^(\d{4})-(\d{2})$/);
        if (dateMatch) {
          const year = parseInt(dateMatch[1]);
          const month = parseInt(dateMatch[2]);
          console.log(`[Purse Plugin] \u5F00\u59CB\u8865\u5168\u7F3A\u5931\u7684\u65E5\u671F: ${year}-${month.toString().padStart(2, "0")}`);
          cleanedContent = await this.completeMissingDates(cleanedContent, year, month);
        } else {
          console.warn(`[Purse Plugin] date \u5C5E\u6027\u683C\u5F0F\u4E0D\u6B63\u786E\uFF0C\u5E94\u4E3A yyyy-MM \u683C\u5F0F: ${dateStr}`);
        }
      }
      if (cleanedContent !== content) {
        console.log(`[Purse Plugin] \u6587\u4EF6\u5185\u5BB9\u5DF2\u66F4\u65B0\uFF0C\u4FDD\u5B58\u6587\u4EF6: ${file.path}`);
        await this.app.vault.modify(file, cleanedContent);
      }
    } else {
      console.error(`[Purse Plugin] \u6587\u4EF6\u683C\u5F0F\u6821\u9A8C\u5931\u8D25: ${file.path}`, result.reason);
    }
    return result;
  }
  /**
   * 补全缺失的日期
   */
  async completeMissingDates(content, year, month) {
    console.log(`[Purse Plugin] \u5F00\u59CB\u8865\u5168\u7F3A\u5931\u7684\u65E5\u671F: ${year}-${month.toString().padStart(2, "0")}`);
    const lines = content.split("\n");
    const daysInMonth = new Date(year, month, 0).getDate();
    console.log(`[Purse Plugin] \u8BE5\u6708\u5171\u6709 ${daysInMonth} \u5929`);
    const existingDates = /* @__PURE__ */ new Map();
    for (let i = 0; i < lines.length; i++) {
      const dateMatch = lines[i].match(/^## (\d+)号$/);
      if (dateMatch) {
        const day = parseInt(dateMatch[1]);
        if (day >= 1 && day <= daysInMonth) {
          existingDates.set(day, i);
        }
      }
    }
    console.log(`[Purse Plugin] \u5DF2\u5B58\u5728\u7684\u65E5\u671F: ${Array.from(existingDates.keys()).sort((a, b) => a - b).join(", ") || "\u65E0"}`);
    const missingDates = [];
    for (let day = 1; day <= daysInMonth; day++) {
      if (!existingDates.has(day)) {
        missingDates.push(day);
      }
    }
    if (missingDates.length === 0) {
      console.log("[Purse Plugin] \u6240\u6709\u65E5\u671F\u90FD\u5DF2\u5B58\u5728\uFF0C\u65E0\u9700\u8865\u5168");
      return content;
    }
    console.log(`[Purse Plugin] \u7F3A\u5931\u7684\u65E5\u671F: ${missingDates.join(", ")}\uFF0C\u5171 ${missingDates.length} \u4E2A`);
    const tableHeader = "| \u7C7B\u578B | \u5206\u7C7B | \u6807\u7B7E | \u6570\u989D | \u5907\u6CE8 |";
    const tableSeparator = "| --- | --- | --- | --- | --- |";
    const newLines = [...lines];
    const findDateTableEnd = (startIndex) => {
      let inTable = false;
      let foundHeaderSeparator = false;
      for (let i = startIndex + 1; i < newLines.length; i++) {
        const trimmedLine = newLines[i].trim();
        if (trimmedLine.match(/^## \d+号$/)) {
          return i;
        }
        if (!inTable && this.isPurseTableHeader(trimmedLine)) {
          inTable = true;
          continue;
        }
        if (inTable && !foundHeaderSeparator && trimmedLine.match(/^\|(\s*[\-:]+\s*\|)+$/)) {
          foundHeaderSeparator = true;
          continue;
        }
        if (foundHeaderSeparator) {
          if (trimmedLine === "") {
            return i + 1;
          }
          const rowMatch = trimmedLine.match(/^\| (支出|收入) \| (.+) \| (.*) \| (\d+\.\d{2}) \| (.*) \|$/);
          if (rowMatch) {
            continue;
          } else if (trimmedLine.startsWith("|")) {
            return i + 1;
          }
        }
      }
      return newLines.length;
    };
    for (const day of missingDates) {
      let insertIndex = -1;
      let maxSmallerDay = 0;
      let maxSmallerIndex = -1;
      for (const [existingDay, lineIndex] of existingDates.entries()) {
        if (existingDay < day && existingDay > maxSmallerDay) {
          maxSmallerDay = existingDay;
          maxSmallerIndex = lineIndex;
        }
      }
      if (maxSmallerIndex >= 0) {
        insertIndex = findDateTableEnd(maxSmallerIndex);
      } else {
        for (let i = 0; i < newLines.length; i++) {
          if (newLines[i].trim() === "# \u6536\u652F\u660E\u7EC6") {
            insertIndex = i + 1;
            break;
          }
        }
      }
      if (insertIndex >= 0) {
        const dateSection = [
          `## ${day}\u53F7`,
          "",
          tableHeader,
          tableSeparator,
          ""
        ];
        newLines.splice(insertIndex, 0, ...dateSection);
        for (const [existingDay, lineIndex] of existingDates.entries()) {
          if (lineIndex >= insertIndex) {
            existingDates.set(existingDay, lineIndex + dateSection.length);
          }
        }
        existingDates.set(day, insertIndex);
        console.log(`[Purse Plugin] \u5DF2\u8865\u5168\u65E5\u671F: ${day}\u53F7\uFF0C\u63D2\u5165\u4F4D\u7F6E: ${insertIndex}`);
      } else {
        console.warn(`[Purse Plugin] \u65E0\u6CD5\u627E\u5230\u65E5\u671F ${day}\u53F7 \u7684\u63D2\u5165\u4F4D\u7F6E`);
      }
    }
    console.log(`[Purse Plugin] \u65E5\u671F\u8865\u5168\u5B8C\u6210\uFF0C\u5171\u8865\u5168 ${missingDates.length} \u4E2A\u65E5\u671F`);
    return newLines.join("\n");
  }
  /**
   * 检查是否是收支明细表头（忽略空格）
   */
  isPurseTableHeader(line) {
    if (!line.startsWith("|") || !line.endsWith("|")) {
      return false;
    }
    const columns = line.split("|").map((col) => col.trim()).filter((col) => col.length > 0);
    return columns.length === 5 && columns[0] === "\u7C7B\u578B" && columns[1] === "\u5206\u7C7B" && columns[2] === "\u6807\u7B7E" && columns[3] === "\u6570\u989D" && columns[4] === "\u5907\u6CE8";
  }
  /**
   * 检查文件内容格式
   */
  checkFormat(content) {
    console.log("[Purse Plugin] \u5F00\u59CB\u68C0\u67E5\u6587\u4EF6\u5185\u5BB9\u683C\u5F0F");
    const lines = content.split("\n");
    if (!content.includes("# \u6536\u652F\u660E\u7EC6")) {
      console.error('[Purse Plugin] \u683C\u5F0F\u6821\u9A8C\u5931\u8D25: \u7F3A\u5C11\u4E3B\u6807\u9898 "# \u6536\u652F\u660E\u7EC6"');
      return {
        isValid: false,
        reason: '\u7F3A\u5C11\u4E3B\u6807\u9898 "# \u6536\u652F\u660E\u7EC6"'
      };
    }
    console.log("[Purse Plugin] \u2713 \u4E3B\u6807\u9898\u68C0\u67E5\u901A\u8FC7");
    const dateHeaderPattern = /^## \d+号$/;
    let hasDateHeader = false;
    let inTable = false;
    let foundTableHeader = false;
    let foundHeaderSeparator = false;
    let hasValidRow = false;
    let invalidRowLine = -1;
    let invalidRowContent = "";
    let afterDateHeader = false;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmedLine = line.trim();
      if (dateHeaderPattern.test(trimmedLine)) {
        hasDateHeader = true;
        inTable = false;
        foundTableHeader = false;
        foundHeaderSeparator = false;
        afterDateHeader = true;
        continue;
      }
      if (afterDateHeader && trimmedLine === "") {
        continue;
      }
      if (afterDateHeader && this.isPurseTableHeader(trimmedLine)) {
        foundTableHeader = true;
        inTable = true;
        afterDateHeader = false;
        continue;
      }
      if (afterDateHeader && trimmedLine !== "") {
        afterDateHeader = false;
      }
      if (inTable && foundTableHeader && trimmedLine.match(/^\|(\s*[\-:]+\s*\|)+$/)) {
        foundHeaderSeparator = true;
        continue;
      }
      if (inTable && foundTableHeader && foundHeaderSeparator) {
        if (trimmedLine === "") {
          let j = i + 1;
          while (j < lines.length && lines[j].trim() === "") {
            j++;
          }
          if (j < lines.length && dateHeaderPattern.test(lines[j].trim())) {
            inTable = false;
            foundTableHeader = false;
            foundHeaderSeparator = false;
          }
          continue;
        }
        if (dateHeaderPattern.test(trimmedLine)) {
          inTable = false;
          foundTableHeader = false;
          foundHeaderSeparator = false;
          hasDateHeader = true;
          afterDateHeader = true;
          continue;
        }
        if (trimmedLine.startsWith("|")) {
          const rowMatch = trimmedLine.match(/^\| (支出|收入) \| (.+) \| (.*) \| (\d+\.\d{2}) \| (.*) \|$/);
          if (rowMatch) {
            hasValidRow = true;
          } else {
            invalidRowLine = i + 1;
            invalidRowContent = trimmedLine;
            const errorMsg = `\u7B2C ${invalidRowLine} \u884C\u683C\u5F0F\u4E0D\u6B63\u786E\uFF1A\u8868\u683C\u6570\u636E\u884C\u683C\u5F0F\u5E94\u4E3A "| \u7C7B\u578B | \u5206\u7C7B | \u6807\u7B7E | \u6570\u989D | \u5907\u6CE8 |"\uFF0C\u5176\u4E2D\u7C7B\u578B\u4E3A"\u652F\u51FA"\u6216"\u6536\u5165"\uFF0C\u5206\u7C7B\u548C\u6570\u989D\u4E3A\u5FC5\u586B\uFF0C\u6807\u7B7E\u548C\u5907\u6CE8\u53EF\u4EE5\u4E3A\u7A7A\uFF0C\u6570\u989D\u4E3A\u4E24\u4F4D\u5C0F\u6570\u3002\u5F53\u524D\u884C\uFF1A${invalidRowContent.substring(0, 50)}${invalidRowContent.length > 50 ? "..." : ""}`;
            console.error(`[Purse Plugin] \u683C\u5F0F\u6821\u9A8C\u5931\u8D25: ${errorMsg}`);
            return {
              isValid: false,
              reason: errorMsg
            };
          }
        } else {
          inTable = false;
          foundTableHeader = false;
          foundHeaderSeparator = false;
        }
      }
    }
    if (!hasDateHeader) {
      console.error('[Purse Plugin] \u683C\u5F0F\u6821\u9A8C\u5931\u8D25: \u7F3A\u5C11\u65E5\u671F\u6807\u9898\uFF08\u683C\u5F0F\u5E94\u4E3A "## xx\u53F7"\uFF0C\u5982 "## 1\u53F7"\uFF09');
      return {
        isValid: false,
        reason: '\u7F3A\u5C11\u65E5\u671F\u6807\u9898\uFF08\u683C\u5F0F\u5E94\u4E3A "## xx\u53F7"\uFF0C\u5982 "## 1\u53F7"\uFF09'
      };
    }
    console.log("[Purse Plugin] \u2713 \u65E5\u671F\u6807\u9898\u68C0\u67E5\u901A\u8FC7");
    if (!hasValidRow) {
      console.error("[Purse Plugin] \u683C\u5F0F\u6821\u9A8C\u5931\u8D25: \u7F3A\u5C11\u6709\u6548\u7684\u8868\u683C\u6570\u636E\u884C\u3002\u6BCF\u4E2A\u65E5\u671F\u6807\u9898\u4E0B\u5E94\u81F3\u5C11\u6709\u4E00\u6761\u8BB0\u5F55");
      return {
        isValid: false,
        reason: '\u7F3A\u5C11\u6709\u6548\u7684\u8868\u683C\u6570\u636E\u884C\u3002\u6BCF\u4E2A\u65E5\u671F\u6807\u9898\u4E0B\u5E94\u81F3\u5C11\u6709\u4E00\u6761\u8BB0\u5F55\uFF0C\u683C\u5F0F\u4E3A "| \u652F\u51FA/\u6536\u5165 | \u5206\u7C7B | \u6807\u7B7E | \u6570\u989D(\u4E24\u4F4D\u5C0F\u6570) | \u5907\u6CE8 |"'
      };
    }
    console.log("[Purse Plugin] \u2713 \u6570\u636E\u884C\u68C0\u67E5\u901A\u8FC7");
    console.log("[Purse Plugin] \u2713 \u6587\u4EF6\u683C\u5F0F\u6821\u9A8C\u5168\u90E8\u901A\u8FC7");
    return { isValid: true };
  }
  /**
   * 自定义表格渲染
   */
  customizeTable(table, file, context) {
    var _a;
    const headerRow = table.querySelector("thead tr");
    if (headerRow) {
      const actionTh = document.createElement("th");
      actionTh.textContent = "\u64CD\u4F5C";
      actionTh.className = "purse-action-header";
      headerRow.appendChild(actionTh);
    }
    const tbody = table.querySelector("tbody");
    if (tbody) {
      const rows = Array.from(tbody.querySelectorAll("tr"));
      rows.forEach((row, index) => {
        var _a2, _b, _c, _d, _e;
        const cells = Array.from(row.querySelectorAll("td"));
        if (cells.length < 5)
          return;
        const type = ((_a2 = cells[0].textContent) == null ? void 0 : _a2.trim()) || "";
        const category = ((_b = cells[1].textContent) == null ? void 0 : _b.trim()) || "";
        const tag = ((_c = cells[2].textContent) == null ? void 0 : _c.trim()) || "";
        const amount = ((_d = cells[3].textContent) == null ? void 0 : _d.trim()) || "";
        const note = ((_e = cells[4].textContent) == null ? void 0 : _e.trim()) || "";
        if ((type === "\u652F\u51FA" || type === "\u6536\u5165") && /^\d+\.\d{2}$/.test(amount)) {
          const actionTd = document.createElement("td");
          actionTd.className = "purse-action-cell";
          const buttonContainer = document.createElement("div");
          buttonContainer.className = "purse-action-buttons";
          const editBtn = document.createElement("button");
          editBtn.textContent = "\u7F16\u8F91";
          editBtn.className = "purse-edit-btn";
          editBtn.onclick = () => {
            this.handleEditRow(file, row, type, category, tag, amount, note);
          };
          buttonContainer.appendChild(editBtn);
          const deleteBtn = document.createElement("button");
          deleteBtn.textContent = "\u5220\u9664";
          deleteBtn.className = "purse-delete-btn";
          deleteBtn.onclick = async () => {
            await this.handleDeleteRow(file, row, type, category, tag, amount, note);
          };
          buttonContainer.appendChild(deleteBtn);
          actionTd.appendChild(buttonContainer);
          row.appendChild(actionTd);
        }
      });
    }
    const existingBtn = (_a = table.nextElementSibling) == null ? void 0 : _a.classList.contains("purse-add-btn-container");
    if (existingBtn)
      return;
    const date = this.findDateForTable(table, file);
    const addBtnContainer = document.createElement("div");
    addBtnContainer.className = "purse-add-btn-container";
    const addBtn = document.createElement("button");
    addBtn.textContent = "\u6DFB\u52A0";
    addBtn.className = "purse-add-btn";
    addBtn.onclick = () => {
      this.handleAddRecord(file, date);
    };
    addBtnContainer.appendChild(addBtn);
    table.insertAdjacentElement("afterend", addBtnContainer);
  }
  /**
   * 查找表格对应的日期
   */
  findDateForTable(table, file) {
    var _a, _b;
    let element = table;
    while (element) {
      element = element.previousElementSibling;
      if (element && element.tagName === "H2") {
        const text = ((_a = element.textContent) == null ? void 0 : _a.trim()) || "";
        const match = text.match(/^(\d+)号$/);
        if (match) {
          return match[1];
        }
      }
    }
    let parent = table.parentElement;
    while (parent) {
      const h2 = parent.querySelector("h2");
      if (h2) {
        const text = ((_b = h2.textContent) == null ? void 0 : _b.trim()) || "";
        const match = text.match(/^(\d+)号$/);
        if (match) {
          return match[1];
        }
      }
      parent = parent.parentElement;
    }
    return "1";
  }
  /**
   * 处理删除行
   */
  async handleDeleteRow(file, row, type, category, tag, amount, note) {
    const confirmed = await new Promise((resolve) => {
      const modal = new DeleteConfirmModal(this.app, resolve);
      modal.open();
    });
    if (confirmed) {
      const rowContent = `| ${type} | ${category} | ${tag} | ${amount} | ${note} |`;
      const content = await this.app.vault.read(file);
      const lines = content.split("\n");
      for (let i = 0; i < lines.length; i++) {
        if (lines[i].trim() === rowContent.trim()) {
          lines.splice(i, 1);
          const modifiedContent = lines.join("\n");
          await this.app.vault.modify(file, modifiedContent);
          await this.formatFile(file);
          break;
        }
      }
      const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (view) {
        view.previewMode.rerender(true);
      }
      new import_obsidian3.Notice("\u8BB0\u5F55\u5DF2\u5220\u9664");
    }
  }
  /**
   * 处理编辑行
   */
  handleEditRow(file, row, type, category, tag, amount, note) {
    const oldRowContent = `| ${type} | ${category} | ${tag} | ${amount} | ${note} |`;
    const date = this.findDateForTable(row.closest("table"), file);
    const modal = new EditRecordModal(this.app, this, file, date, type, category, tag, amount, note, oldRowContent, async () => {
      await this.formatFile(file);
      const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (view) {
        view.previewMode.rerender(true);
      }
    });
    modal.open();
  }
  /**
   * 处理添加记录
   */
  handleAddRecord(file, date) {
    const modal = new AddRecordModal(this.app, this, file, date, -1, async () => {
      await this.formatFile(file);
      const view = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
      if (view) {
        view.previewMode.rerender(true);
      }
    });
    modal.open();
  }
  /**
   * 创建收支明细文件
   */
  async createPurseFile(year, month) {
    const daysInMonth = new Date(year, month, 0).getDate();
    const dateStr = `${year}-${String(month).padStart(2, "0")}`;
    const monthName = `${String(month).padStart(2, "0")}\u6708`;
    let content = "---\n";
    content += "purse: true\n";
    content += `date: ${dateStr}
`;
    content += "---\n\n";
    content += "# \u6536\u652F\u660E\u7EC6\n\n";
    const tableHeader = "| \u7C7B\u578B | \u5206\u7C7B | \u6807\u7B7E | \u6570\u989D | \u5907\u6CE8 |";
    const tableSeparator = "| --- | --- | --- | --- | --- |";
    for (let day = 1; day <= daysInMonth; day++) {
      content += `## ${day}\u53F7

`;
      content += `${tableHeader}
`;
      content += `${tableSeparator}

`;
    }
    const fileName = `${monthName}.md`;
    const file = await this.app.vault.create(fileName, content);
    await this.app.workspace.openLinkText(fileName, "", true);
    console.log(`[Purse Plugin] \u5DF2\u521B\u5EFA\u6587\u4EF6: ${fileName}, \u65E5\u671F: ${dateStr}`);
  }
};
